In [1]:
#importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#reading the dataset and storing it into dataframme df
df=pd.read_excel("../Data set/default_of_credit_card_clients.xls")

In [3]:
#first 10 rows from df dataframe
df.head(10)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0  798fc410-45c1      20000    2          2         1   24     2      2   
1  8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2  85698822-43f5      90000    2          2         2   34     0      0   
3  0737c11b-be42      50000    2          2         1   37     0      0   
4  3b7f77cc-dbc0      50000    1          2         1   57    -1      0   
5  ceae2946-47e4      50000    1          1         2   37     0      0   
6  d3b8ce26-9c89     500000    1          1         2   29     0      0   
7  d6e1911b-54d0     100000    2          2         2   23     0     -1   
8  8421d3b3-2b54     140000    2          3         1   28     0      0   
9  62a2fd79-cd90      20000    1          3         2   35    -2     -2   

   PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0     -1     -1  ...          0          0          0         0       689   
1      0      0  ...       3272       3455       3261         0      1000   
2      0      0  ...      14331      14948      15549      1518      1500   
3      0      0  ...      28314      28959      29547      2000      2019   
4     -1      0  ...      20940      19146      19131      2000     36681   
5      0      0  ...      19394      19619      20024      2500      1815   
6      0      0  ...     542653     483003     473944     55000     40000   
7     -1      0  ...        221       -159        567       380       601   
8      2      0  ...      12211      11793       3719      3329         0   
9     -2     -2  ...          0      13007      13912         0         0   

   PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0         0         0         0         0                           1  
1      1000      1000         0      2000                           1  
2      1000      1000      1000      5000                           0  
3      1200      1100      1069      1000                           0  
4     10000      9000       689       679                           0  
5       657      1000      1000       800                           0  
6     38000     20239     13750     13770                           0  
7         0       581      1687      1542                           0  
8       432      1000      1000      1000                           0  
9         0     13007      1122         0                           0  

[10 rows x 25 columns]

In [4]:
np.random.seed(seed=24)

In [5]:
np.random.randint(low=1,high=5,size=100)

array([3, 4, 1, 4, 2, 2, 2, 1, 4, 4, 1, 4, 4, 3, 4, 4, 4, 4, 4, 4, 2, 3,
       4, 4, 2, 4, 2, 4, 1, 1, 3, 1, 4, 2, 2, 1, 4, 3, 2, 2, 3, 3, 2, 3,
       4, 2, 3, 4, 1, 3, 4, 2, 2, 4, 1, 2, 3, 3, 2, 1, 2, 4, 2, 1, 4, 3,
       1, 2, 1, 3, 4, 2, 3, 4, 1, 3, 2, 1, 1, 3, 3, 4, 3, 2, 4, 1, 4, 4,
       4, 4, 1, 4, 3, 2, 4, 4, 3, 3, 2, 4])

In [11]:
np.random.seed(seed=24)
random_integers=np.random.randint(low=1,high=5,size=100)

In [12]:
is_equal_to_3=random_integers==3

In [13]:
is_equal_to_3

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False,  True,  True, False,  True, False,
       False,  True, False, False,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
        True, False, False,  True, False, False, False,  True,  True,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False,  True,  True, False,
       False])

In [14]:
is_equal_to_3[:5]

array([ True, False, False, False, False])

In [15]:
sum(is_equal_to_3)

22

In [16]:
random_integers[is_equal_to_3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [17]:
#Let us check ID column value's counts :
df['ID'].value_counts()

214fc1ca-b25a    2
994330b6-eeec    2
9878723a-0b58    2
ebda7f71-7024    2
f7fe4368-18e7    2
                ..
4281bf75-d3a8    1
71905400-5947    1
1bbe3d6b-e9fa    1
98df2693-d0cf    1
77e07b88-c6b8    1
Name: ID, Length: 29687, dtype: int64

In [18]:
#Let us check if a specific ID has been entered twice :
id_check=df['ID'].value_counts()
id_check==2

214fc1ca-b25a     True
994330b6-eeec     True
9878723a-0b58     True
ebda7f71-7024     True
f7fe4368-18e7     True
                 ...  
4281bf75-d3a8    False
71905400-5947    False
1bbe3d6b-e9fa    False
98df2693-d0cf    False
77e07b88-c6b8    False
Name: ID, Length: 29687, dtype: bool

In [19]:
dupe_mask=id_check==2
dupe_mask[:5]

214fc1ca-b25a    True
994330b6-eeec    True
9878723a-0b58    True
ebda7f71-7024    True
f7fe4368-18e7    True
Name: ID, dtype: bool

In [20]:
id_check.index[dupe_mask]

Index(['214fc1ca-b25a', '994330b6-eeec', '9878723a-0b58', 'ebda7f71-7024',
       'f7fe4368-18e7', 'f5e3478e-cf68', 'b4937915-ad67', 'ff8b7170-ce3a',
       '956cbf4a-d24e', '999b7824-373c',
       ...
       '26bde6da-f148', '0a2dceda-b597', '297edb0f-3bb1', 'f86688f1-8742',
       'f6032812-464e', '9ac5d94f-ed71', '6d1fc219-67b0', '1512a948-a7e4',
       '97d1d2eb-c72f', '9c53fb07-9b73'],
      dtype='object', length=313)

In [21]:
dupe_ids=id_check.index[dupe_mask]
dupe_ids=list(dupe_ids)
dupe_ids

['214fc1ca-b25a',
 '994330b6-eeec',
 '9878723a-0b58',
 'ebda7f71-7024',
 'f7fe4368-18e7',
 'f5e3478e-cf68',
 'b4937915-ad67',
 'ff8b7170-ce3a',
 '956cbf4a-d24e',
 '999b7824-373c',
 '4f249cbc-5e9c',
 '998fa9b2-b341',
 '4ae0efd7-2651',
 'c8bb762f-3ef9',
 '04299d54-61d4',
 '86477d4e-795e',
 '68ff6fcd-1d49',
 '5b8dce34-2ded',
 '1fb3e3e6-a68d',
 'ac821a7b-b399',
 'e7f574b9-0581',
 '4e2380e6-a8cf',
 'e850d228-6879',
 'feac3745-a2be',
 '382b378c-6383',
 '355fe35a-5db7',
 'b46f955f-9e8a',
 '96970f37-abaa',
 'fa286931-8ded',
 'dda76366-a407',
 'dd019fd7-f591',
 'e07a0034-42af',
 'a51dbaae-d88b',
 '775d61d0-4715',
 '7b7cc3cd-0b76',
 '415c344e-309f',
 '5795a795-bfa0',
 '315e4f9d-2b0b',
 '266c34a2-16c9',
 '90330d02-82d9',
 '56945919-0933',
 '85bd7f39-2e9b',
 '4fcef74d-0b3d',
 '3cfed539-ad58',
 '1b22b0ab-aba3',
 'a9870d3e-b4d1',
 'ad63957b-ea9a',
 'accba688-8ec1',
 '28866128-6286',
 '91321f74-e4a4',
 'bae9475e-7cad',
 'db903e22-a55a',
 '77222291-e191',
 '84dc097a-dee3',
 'dab579ee-1645',
 '73ea498f

In [22]:
df.loc[df['ID'].isin(dupe_ids),:].head(10)


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE          PAY_1  \
141  26bde6da-f148     180000    1          2         2   28             -1   
196  42009c72-651f     150000    2          2         1   34             -2   
241  26bde6da-f148          0    0          0         0    0              0   
296  42009c72-651f          0    0          0         0    0              0   
323  73ed1381-3a3f     230000    2          2         1   28              0   
340  4f95b36b-ab10     240000    2          2         2   30             -2   
398  8d3a2576-a958     210000    2          2         1   30  Not available   
423  73ed1381-3a3f          0    0          0         0    0              0   
440  4f95b36b-ab10          0    0          0         0    0              0   
498  8d3a2576-a958          0    0          0         0    0              0   

     PAY_2  PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
141     -1     -1     -1  ...        332        416        416         0   
196     -2     -2     -2  ...        116          0       1500         0   
241      0      0      0  ...          0          0          0         0   
296      0      0      0  ...          0          0          0         0   
323      0      0     -2  ...       2100        767       6173      1710   
340     -2     -2     -2  ...          0         92          0        92   
398      0      0      0  ...      91143      82733      74125      4002   
423      0      0      0  ...          0          0          0         0   
440      0      0      0  ...          0          0          0         0   
498      0      0      0  ...          0          0          0         0   

     PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
141       416       332       500      3500       832   
196         0       116         0      1500         0   
241         0         0         0         0         0   
296         0         0         0         0         0   
323      1100      1000       767      6173      1000   
340        92         0        92         0      1883   
398      5000      3500      3000      2700      5000   
423         0         0         0         0         0   
440         0         0         0         0         0   
498         0         0         0         0         0   

     default payment next month  
141                           0  
196                           0  
241                           0  
296                           0  
323                           1  
340                           0  
398                           0  
423                           0  
440                           0  
498                           0  

[10 rows x 25 columns]

In [23]:
df_zero_mask=df==0

In [24]:
feature_zero_mask=df_zero_mask.iloc[:,1:].all(axis=1)
sum(feature_zero_mask)

315

In [25]:
#check Non-zero values in our dataframe
df_clean_1 = df.loc[~feature_zero_mask,:].copy()
df_clean_1

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0      798fc410-45c1      20000    2          2         1   24     2      2   
1      8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2      85698822-43f5      90000    2          2         2   34     0      0   
3      0737c11b-be42      50000    2          2         1   37     0      0   
4      3b7f77cc-dbc0      50000    1          2         1   57    -1      0   
...              ...        ...  ...        ...       ...  ...   ...    ...   
29995  ecff42d0-bdc6     220000    1          3         1   39     0      0   
29996  99d1fa0e-222b     150000    1          3         2   43    -1     -1   
29997  95cdd3e7-4f24      30000    1          2         2   37     4      3   
29998  00d03f02-04cd      80000    1          3         1   41     1     -1   
29999  15d69f9f-5ad3      50000    1          2         1   46     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1     -1  ...          0          0          0         0       689   
1          0      0  ...       3272       3455       3261         0      1000   
2          0      0  ...      14331      14948      15549      1518      1500   
3          0      0  ...      28314      28959      29547      2000      2019   
4         -1      0  ...      20940      19146      19131      2000     36681   
...      ...    ...  ...        ...        ...        ...       ...       ...   
29995      0      0  ...      88004      31237      15980      8500     20000   
29996     -1     -1  ...       8979       5190          0      1837      3526   
29997      2     -1  ...      20878      20582      19357         0         0   
29998      0      0  ...      52774      11855      48944     85900      3409   
29999      0      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[29685 rows x 25 columns]

In [26]:
#Count distinct ID's
df_clean_1['ID'].nunique()

29685

In [27]:
df['PAY_1'].unique()

array([2, -1, 0, -2, 1, 'Not available', 3, 4, 8, 7, 5, 6], dtype=object)

In [28]:
valid_pay_1_mask = df_clean_1['PAY_1'] != 'Not available'
valid_pay_1_mask[0:5]

0    True
1    True
2    True
3    True
4    True
Name: PAY_1, dtype: bool

In [29]:
df_clean_2 = df_clean_1.loc[valid_pay_1_mask,:].copy()


In [30]:
df_clean_2


ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE PAY_1  PAY_2  \
0      798fc410-45c1      20000    2          2         1   24     2      2   
1      8a8c8f3b-8eb4     120000    2          2         2   26    -1      2   
2      85698822-43f5      90000    2          2         2   34     0      0   
3      0737c11b-be42      50000    2          2         1   37     0      0   
4      3b7f77cc-dbc0      50000    1          2         1   57    -1      0   
...              ...        ...  ...        ...       ...  ...   ...    ...   
29995  ecff42d0-bdc6     220000    1          3         1   39     0      0   
29996  99d1fa0e-222b     150000    1          3         2   43    -1     -1   
29997  95cdd3e7-4f24      30000    1          2         2   37     4      3   
29998  00d03f02-04cd      80000    1          3         1   41     1     -1   
29999  15d69f9f-5ad3      50000    1          2         1   46     0      0   

       PAY_3  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1     -1  ...          0          0          0         0       689   
1          0      0  ...       3272       3455       3261         0      1000   
2          0      0  ...      14331      14948      15549      1518      1500   
3          0      0  ...      28314      28959      29547      2000      2019   
4         -1      0  ...      20940      19146      19131      2000     36681   
...      ...    ...  ...        ...        ...        ...       ...       ...   
29995      0      0  ...      88004      31237      15980      8500     20000   
29996     -1     -1  ...       8979       5190          0      1837      3526   
29997      2     -1  ...      20878      20582      19357         0         0   
29998      0      0  ...      52774      11855      48944     85900      3409   
29999      0      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[26664 rows x 25 columns]

In [32]:
df_clean_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26664 entries, 0 to 29999
Data columns (total 25 columns):
ID                            26664 non-null object
LIMIT_BAL                     26664 non-null int64
SEX                           26664 non-null int64
EDUCATION                     26664 non-null int64
MARRIAGE                      26664 non-null int64
AGE                           26664 non-null int64
PAY_1                         26664 non-null object
PAY_2                         26664 non-null int64
PAY_3                         26664 non-null int64
PAY_4                         26664 non-null int64
PAY_5                         26664 non-null int64
PAY_6                         26664 non-null int64
BILL_AMT1                     26664 non-null int64
BILL_AMT2                     26664 non-null int64
BILL_AMT3                     26664 non-null int64
BILL_AMT4                     26664 non-null int64
BILL_AMT5                     26664 non-null int64
BILL_AMT6             

In [33]:
df_clean_2['PAY_1'] = df_clean_2['PAY_1'].astype('int64')
df_clean_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26664 entries, 0 to 29999
Data columns (total 25 columns):
ID                            26664 non-null object
LIMIT_BAL                     26664 non-null int64
SEX                           26664 non-null int64
EDUCATION                     26664 non-null int64
MARRIAGE                      26664 non-null int64
AGE                           26664 non-null int64
PAY_1                         26664 non-null int64
PAY_2                         26664 non-null int64
PAY_3                         26664 non-null int64
PAY_4                         26664 non-null int64
PAY_5                         26664 non-null int64
PAY_6                         26664 non-null int64
BILL_AMT1                     26664 non-null int64
BILL_AMT2                     26664 non-null int64
BILL_AMT3                     26664 non-null int64
BILL_AMT4                     26664 non-null int64
BILL_AMT5                     26664 non-null int64
BILL_AMT6              

In [34]:
df_clean_2['EDUCATION'].value_counts()


2    12458
1     9412
3     4380
5      245
4      115
6       43
0       11
Name: EDUCATION, dtype: int64

In [35]:
df_clean_2['EDUCATION'].replace(to_replace=0, value=6, inplace=True)
df_clean_2['EDUCATION'].value_counts()

2    12458
1     9412
3     4380
5      245
4      115
6       54
Name: EDUCATION, dtype: int64

In [36]:
df_clean_2['MARRIAGE'].value_counts()


2    14158
1    12172
3      286
0       48
Name: MARRIAGE, dtype: int64

In [37]:
df_clean_2['EDUCATION_CAT'] = 'none'

In [38]:
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)

EDUCATION EDUCATION_CAT
0          2          none
1          2          none
2          2          none
3          2          none
4          2          none
5          1          none
6          1          none
7          2          none
8          3          none
9          3          none

In [39]:
cat_mapping = {
    1: "graduate school",
    2: "university",
    3: "high school",
    4: "others"
}

In [40]:
df_clean_2['EDUCATION_CAT'] = df_clean_2['EDUCATION'].map(cat_mapping)
df_clean_2[['EDUCATION', 'EDUCATION_CAT']].head(10)

EDUCATION    EDUCATION_CAT
0          2       university
1          2       university
2          2       university
3          2       university
4          2       university
5          1  graduate school
6          1  graduate school
7          2       university
8          3      high school
9          3      high school

In [41]:
#getting df to get dummy indicators.
edu_ohe = pd.get_dummies(df_clean_2['EDUCATION_CAT'])
edu_ohe.head(10)

graduate school  high school  others  university
0                0            0       0           1
1                0            0       0           1
2                0            0       0           1
3                0            0       0           1
4                0            0       0           1
5                1            0       0           0
6                1            0       0           0
7                0            0       0           1
8                0            1       0           0
9                0            1       0           0

In [42]:
#Combine two Series along the columns 
df_with_ohe = pd.concat([df_clean_2, edu_ohe], axis=1)
df_with_ohe

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  \
0      798fc410-45c1      20000    2          2         1   24      2      2   
1      8a8c8f3b-8eb4     120000    2          2         2   26     -1      2   
2      85698822-43f5      90000    2          2         2   34      0      0   
3      0737c11b-be42      50000    2          2         1   37      0      0   
4      3b7f77cc-dbc0      50000    1          2         1   57     -1      0   
...              ...        ...  ...        ...       ...  ...    ...    ...   
29995  ecff42d0-bdc6     220000    1          3         1   39      0      0   
29996  99d1fa0e-222b     150000    1          3         2   43     -1     -1   
29997  95cdd3e7-4f24      30000    1          2         2   37      4      3   
29998  00d03f02-04cd      80000    1          3         1   41      1     -1   
29999  15d69f9f-5ad3      50000    1          2         1   46      0      0   

       PAY_3  PAY_4  ...  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0         -1     -1  ...         0         0         0         0   
1          0      0  ...      1000      1000         0      2000   
2          0      0  ...      1000      1000      1000      5000   
3          0      0  ...      1200      1100      1069      1000   
4         -1      0  ...     10000      9000       689       679   
...      ...    ...  ...       ...       ...       ...       ...   
29995      0      0  ...      5003      3047      5000      1000   
29996     -1     -1  ...      8998       129         0         0   
29997      2     -1  ...     22000      4200      2000      3100   
29998      0      0  ...      1178      1926     52964      1804   
29999      0      0  ...      1430      1000      1000      1000   

       default payment next month  EDUCATION_CAT  graduate school  \
0                               1     university                0   
1                               1     university                0   
2                               0     university                0   
3                               0     university                0   
4                               0     university                0   
...                           ...            ...              ...   
29995                           0    high school                0   
29996                           0    high school                0   
29997                           1     university                0   
29998                           1    high school                0   
29999                           1     university                0   

       high school  others  university  
0                0       0           1  
1                0       0           1  
2                0       0           1  
3                0       0           1  
4                0       0           1  
...            ...     ...         ...  
29995            1       0           0  
29996            1       0           0  
29997            0       0           1  
29998            1       0           0  
29999            0       0           1  

[26664 rows x 30 columns]

In [43]:
df_with_ohe[['EDUCATION_CAT', 'graduate school',
             'high school', 'university', 'others']].head(10)

EDUCATION_CAT  graduate school  high school  university  others
0       university                0            0           1       0
1       university                0            0           1       0
2       university                0            0           1       0
3       university                0            0           1       0
4       university                0            0           1       0
5  graduate school                1            0           0       0
6  graduate school                1            0           0       0
7       university                0            0           1       0
8      high school                0            1           0       0
9      high school                0            1           0       0

In [44]:
#Importing the cleaned version to CSV File
df_with_ohe.to_csv('cleaned_data.csv', index=False)